/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ShareOnlinePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var fs = __toESM(require("fs"));
var path = __toESM(require("path"));
var os = __toESM(require("os"));
var ShareOnlinePlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "export-current-note-to-desktop",
      name: "\u5BFC\u51FA\u5F53\u524D\u7B14\u8BB0\u5230\u684C\u9762",
      callback: () => this.exportCurrentNote()
    });
    this.addCommand({
      id: "export-note-to-desktop",
      name: "\u9009\u62E9\u7B14\u8BB0\u5BFC\u51FA\u5230\u684C\u9762",
      callback: () => new ExportNoteModal(this.app, this).open()
    });
  }
  async exportCurrentNote() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian.Notice("\u6CA1\u6709\u6253\u5F00\u7684\u7B14\u8BB0");
      return;
    }
    await this.exportFile(activeFile);
  }
  async exportFile(file) {
    try {
      const content = await this.app.vault.read(file);
      const desktopPath = path.join(os.homedir(), "Desktop", file.name);
      fs.writeFileSync(desktopPath, content, "utf8");
      new import_obsidian.Notice(`\u5DF2\u5BFC\u51FA\u5230\u684C\u9762\uFF1A${file.name}`);
    } catch (err) {
      new import_obsidian.Notice(`\u5BFC\u51FA\u5931\u8D25\uFF1A${err.message}`);
      console.error(err);
    }
  }
  onunload() {
  }
};
var ExportNoteModal = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("\u8F93\u5165\u7B14\u8BB0\u540D\u79F0\u641C\u7D22...");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.plugin.exportFile(file);
  }
};
